services:
  postgres:
    image: postgres:15-alpine
    restart: always
    env_file:
      - ./compose/.envs/.postgres
    volumes:
      - postgresql_data:/var/lib/postgresql/data
      - ./compose/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '5434:5432'
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "myuser", "-d", "mydb" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

  pgbouncer:
    image: bitnami/pgbouncer
    restart: always
    depends_on:
      - postgres
    env_file:
      - ./compose/.envs/.pgbouncer
    ports:
      - '6432:6432'
    volumes:
      - ./compose/pgbouncer/userlist.txt:/bitnami/pgbouncer/userlist.txt
      - ./compose/pgbouncer/pgbouncer.ini:/bitnami/pgbouncer/conf/pgbouncer.ini

  pgwatch:
    image: cybertec/pgwatch2-postgres
    restart: always
    depends_on:
      - postgres
      - pgbouncer
    ports:
      - '8080:8080'
      - '3000:3000'
  
  pgbackups3:
    image: schickling/postgres-backup-s3
    links:
      - postgres
    env_file:
      - ./compose/.envs/.pgbackups

volumes:
  postgresql_data:
